name: CVE Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM

jobs:
  cve-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
    
    - name: Build Android project
      run: |
        ./gradlew assembleDebug
    
    - name: Run Trivy filesystem scan
      run: |
        trivy fs --format json --output trivy-fs-report.json .
        trivy fs --format table --output trivy-fs-report.txt .
    
    - name: Run Trivy image scan (if Docker image exists)
      run: |
        if [ -f Dockerfile ]; then
          docker build -t ambient-scribe:latest .
          trivy image --format json --output trivy-image-report.json ambient-scribe:latest
          trivy image --format table --output trivy-image-report.txt ambient-scribe:latest
        else
          echo "No Dockerfile found, skipping image scan"
        fi
    
    - name: Check for High/Critical vulnerabilities
      run: |
        python scripts/cve-checker.py trivy-fs-report.json
    
    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-scan-results
        path: |
          trivy-fs-report.json
          trivy-fs-report.txt
          trivy-image-report.json
          trivy-image-report.txt
        retention-days: 30
    
    - name: Comment PR with scan results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let comment = '## 🔒 Security Scan Results\n\n';
          
          if (fs.existsSync('trivy-fs-report.txt')) {
            const fsReport = fs.readFileSync('trivy-fs-report.txt', 'utf8');
            comment += '### Filesystem Scan\n```\n' + fsReport + '\n```\n\n';
          }
          
          if (fs.existsSync('trivy-image-report.txt')) {
            const imageReport = fs.readFileSync('trivy-image-report.txt', 'utf8');
            comment += '### Container Image Scan\n```\n' + imageReport + '\n```\n\n';
          }
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
