name: SBOM Generation and Dependency Attestations

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]
  schedule:
    - cron: '0 4 * * 1'  # Weekly on Monday at 4 AM

jobs:
  sbom-generation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install CycloneDX CLI
      run: |
        wget https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64 -O cyclonedx
        chmod +x cyclonedx
        sudo mv cyclonedx /usr/local/bin/
    
    - name: Build project
      run: |
        ./gradlew assembleDebug
    
    - name: Generate SBOM for Java dependencies
      run: |
        cyclonedx java --output-format json --output-file sbom-java.json .
        cyclonedx java --output-format xml --output-file sbom-java.xml .
    
    - name: Generate SBOM for Gradle dependencies
      run: |
        cyclonedx gradle --output-format json --output-file sbom-gradle.json .
        cyclonedx gradle --output-format xml --output-file sbom-gradle.xml .
    
    - name: Generate SBOM for Android dependencies
      run: |
        cyclonedx android --output-format json --output-file sbom-android.json .
        cyclonedx android --output-format xml --output-file sbom-android.xml .
    
    - name: Generate dependency attestations
      run: |
        python scripts/generate_dependency_attestations.py
    
    - name: Validate SBOM files
      run: |
        python scripts/validate_sbom.py sbom-java.json
        python scripts/validate_sbom.py sbom-gradle.json
        python scripts/validate_sbom.py sbom-android.json
    
    - name: Generate SBOM summary report
      run: |
        python scripts/sbom_summary.py
    
    - name: Upload SBOM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sbom-artifacts
        path: |
          sbom-*.json
          sbom-*.xml
          dependency-attestations.json
          sbom-summary.txt
        retention-days: 365
    
    - name: Upload to GitHub Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.upload_url }}
        asset_path: ./sbom-java.json
        asset_name: sbom-java.json
        asset_content_type: application/json
    
    - name: Comment PR with SBOM summary
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let comment = '## 📦 SBOM Generation Report\n\n';
          
          if (fs.existsSync('sbom-summary.txt')) {
            const summary = fs.readFileSync('sbom-summary.txt', 'utf8');
            comment += '### Summary\n```\n' + summary + '\n```\n\n';
          }
          
          comment += '### Generated Artifacts\n';
          comment += '- `sbom-java.json` - Java dependencies SBOM (JSON)\n';
          comment += '- `sbom-java.xml` - Java dependencies SBOM (XML)\n';
          comment += '- `sbom-gradle.json` - Gradle dependencies SBOM (JSON)\n';
          comment += '- `sbom-gradle.xml` - Gradle dependencies SBOM (XML)\n';
          comment += '- `sbom-android.json` - Android dependencies SBOM (JSON)\n';
          comment += '- `sbom-android.xml` - Android dependencies SBOM (XML)\n';
          comment += '- `dependency-attestations.json` - Dependency attestations\n\n';
          comment += 'All artifacts are available in the workflow artifacts.';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
